version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: folio-postgres
    restart: always
    environment:
      POSTGRES_USER: folio_user
      POSTGRES_PASSWORD: folio_password
      POSTGRES_DB: folio_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
